# Server settings (ServerProperties)

logging:
 config: config/logback.xml
 level.*: debug
platform:
  secretKey: game
  vertifyUrl: http://192.168.10.2:7203/user/game/getGameUserInfo
  consumeUrl: http://localhost:8081/comsume

server:
 port: 8081
 address: 0.0.0.0
 sessionTimeout: 30
 contextPath: /center

spring:
 data.mongodb.uri: mongodb://192.168.10.30:27017/game
 redis:
  host: 192.168.10.30
  port: 6379
  password: alan
  database: 2

## Dubbo ???????
spring.dubbo:
  application.name: provider
  registry.address: zookeeper://192.168.10.30:2181
  protocol.name: dubbo
  protocol.port: 20880
  scan: com.gaea.game

    