# Server settings (ServerProperties)
logging:
 config: config/logback.xml
 level.*: debug
platform:
  secretKey: aaaaaaaaaaaaaaa
  vertifyUrl: http://localhost:8081/center/vertify/checkToken
  consumeUrl: http://localhost:8081/comsume

server:
 port: 8081
 address: 0.0.0.0
 sessionTimeout: 30
 contextPath: /center

spring:
 data.mongodb.uri: mongodb://192.168.7.30:27017/cardchess
 redis:
  host: 192.168.7.30
  port: 6379
  password: alan
  database: 2
  
    