# Server settings (ServerProperties)
logging:
 config: config/logback.xml
 level.*: debug
sample:
  samplePackage: org.alan.chess.logic.sample
  samplePath: resources/sample
  roleSaveInterval: 60

tcp:
 port: ${cluster.tcpAddress.port}
 host: ${cluster.tcpAddress.host}

spring:
 data.mongodb.uri: mongodb://192.168.7.30:27017/cardchess
 redis:
  host: localhost
  port: 6379
  password: alan
  database: 2
  
    