# Server settings (ServerProperties)
logging:
 config: config/logback.xml
 level.*: debug
sample:
  samplePackage: com.gaea.game.logic.sample
  samplePath: resources/sample
  roleSaveInterval: 60
platform:
  secretKey: aaaaaaaaaaaaaaa
  vertifyUrl: http://localhost:8081/vertify
  consumeUrl: http://localhost:8081/comsume
logic:
  serverId: 1
  serverName: logic1
  host: 192.168.7.169
  port: 8082
  wsAddress: ws://${logic.host}:${logic.port}/logic/ws
  maxNum: 5000
  centerRegisterUrl: http://localhost:8081/center/node/register

server:
 port: 8082
 address: 0.0.0.0
 sessionTimeout: 30
 contextPath: /logic

spring:
 data.mongodb.uri: mongodb://192.168.7.30:27017/cardchess
 redis:
  host: 192.168.7.30
  port: 6379
  password: alan
  database: 2
  
    